name: letsvote_mobile
description: LetsVote Mobile

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  letsvote:
    path: ../letsvote
  http: ^0.11.0


flutter:
  uses-material-design: true
  assets:
      - config.yaml
