name: letsvote
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: john <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  shelf_route: ^0.14.3
  route: ^0.4.6
  source_gen: ^0.7.2
  json_serializable: ^0.2.5
  json_annotation: ^0.2.1
  http: ^0.11.3
  yaml: ^2.1.0
  requester: ^0.0.1
dev_dependencies:
  build_runner: ^0.5.0
  test: ^0.12.0
